apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrawhisper
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Anveshreddy96/infrawhisper-aiops
    targetRevision: HEAD
    path: helm
  destination:
    server: https://kubernetes.default.svc
    namespace: infrawhisper
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
