replicaCount: 2

image:
  repository: 394824061250.dkr.ecr.us-east-1.amazonaws.com/infrawhisper-api
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

env:
  AWS_REGION_NAME: us-east-1
  DYNAMODB_TABLE: infrawhisper-incidents
  LAMBDA_FUNCTION: infrawhisper-triage-engine
  BEDROCK_MODEL: us.anthropic.claude-sonnet-4-6

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
